In [1]:
import pandas as pd

In [2]:
file = pd.read_csv('../../NAOS/Bstars/DR3data/Tables/New_table_rot.csv', sep=';')
file

          TIC          GaiaDR3Name  Period  ePeriod  t_span
0     4491131   879237740307303040   0.223    0.001      23
1    58105597  2862194144817359872   2.656    0.207      17
2   110798652  5612323414549657728   1.848    0.037      46
3   118269334   107344877838785408   2.961    0.258      17
4   165547989  4543527365639560832   0.972    0.010      47
5   198240464  1625482634333259904   2.243    0.042     237
6   220323146  3326686263650895360   1.891    0.163      44
7   229452839  2242261726411588480   2.238    0.034     293
8   232633722  1421628819152912768   1.617    0.056      93
9   233539736  2156534144822785792   0.316    0.001     254
10  236872887  2244151546381948032   4.919    0.079     153
11  258109545  1220472582737099776   3.126    0.106      46
12  258461221  2250691269744522624   2.259    0.035     289
13  268971806  5517239366958299776   1.287    0.008     105
14  269118344  3234302311683109120   1.806    0.037      44
15  276549422  1959585224012855168   1.175    0.145      19
16  279511712  5480486644608749696   1.603    0.003     473
17  322312868  2218011928739597824   1.913    0.021      88
18  358467049  5290722929205920896   3.630    0.027     241
19  393852409   821254857177030272   2.342    0.439      25
20  394020645  4550114402362108416   1.119    0.013      47
21  407615454  3272902041766301184   1.483    0.092      48

In [6]:
N_cyc = []

for i in range(len(file)):
    n_cycle = file.t_span[i] / file.Period[i]
    N_cyc.append(round(n_cycle, 3))

N_cyc

[103.139,
 6.401,
 24.892,
 5.741,
 48.354,
 105.662,
 23.268,
 130.92,
 57.514,
 803.797,
 31.104,
 14.715,
 127.933,
 81.585,
 24.363,
 16.17,
 295.072,
 46.001,
 66.391,
 10.675,
 42.002,
 32.367]

In [7]:
N_cycle = pd.DataFrame(N_cyc, columns=['N_cycle'])
New_table = pd.concat([file, N_cycle], axis=1)
New_table

          TIC          GaiaDR3Name  Period  ePeriod  t_span  N_cycle
0     4491131   879237740307303040   0.223    0.001      23  103.139
1    58105597  2862194144817359872   2.656    0.207      17    6.401
2   110798652  5612323414549657728   1.848    0.037      46   24.892
3   118269334   107344877838785408   2.961    0.258      17    5.741
4   165547989  4543527365639560832   0.972    0.010      47   48.354
5   198240464  1625482634333259904   2.243    0.042     237  105.662
6   220323146  3326686263650895360   1.891    0.163      44   23.268
7   229452839  2242261726411588480   2.238    0.034     293  130.920
8   232633722  1421628819152912768   1.617    0.056      93   57.514
9   233539736  2156534144822785792   0.316    0.001     254  803.797
10  236872887  2244151546381948032   4.919    0.079     153   31.104
11  258109545  1220472582737099776   3.126    0.106      46   14.715
12  258461221  2250691269744522624   2.259    0.035     289  127.933
13  268971806  5517239366958299776   1.287    0.008     105   81.585
14  269118344  3234302311683109120   1.806    0.037      44   24.363
15  276549422  1959585224012855168   1.175    0.145      19   16.170
16  279511712  5480486644608749696   1.603    0.003     473  295.072
17  322312868  2218011928739597824   1.913    0.021      88   46.001
18  358467049  5290722929205920896   3.630    0.027     241   66.391
19  393852409   821254857177030272   2.342    0.439      25   10.675
20  394020645  4550114402362108416   1.119    0.013      47   42.002
21  407615454  3272902041766301184   1.483    0.092      48   32.367